language: python
python:
  - "3.8"
install:
  - git clone https://github.com/boolector/boolector
  - cd boolector
  - sudo apt-get install python3-dev python3-pip python3-tk python3-lxml python3-six
  - pip install Cython
  - ./contrib/setup-lingeling.sh
  - ./contrib/setup-btor2tools.sh
  - ./configure.sh --python && cd build && make
  - pip install pyboolector
  - cd ../../
script:
  - make
  - sh all_tests.sh
